apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: spring-boot-kotlin-deploy
  name: spring-boot-kotlin-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: spring-boot-kotlin-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: spring-boot-kotlin-deploy
    spec:
      containers:
      - image: rajeshg87/spring-boot-kotlin
        name: spring-boot-kotlin-deploy
        resources: {}
status: {}
